### ISSUE TITLE
Always Request For Password

### ISSUE THREAD

**Issue by LinuxPhreak** [Compewter/VEAL#7]
I have a successful installation on both Ubuntu 18.04 and Debian 9, still working on Fedora and CentOS. 

But after I get a successfully installed I navigate to the address in my browser and it expects me to type in a password. Even when the .env file has nothing for the password. And when I put a password in the file and type it into the password field it still doesn't let me in. It is like simply have a web page with a single password field and a button and doesn't do anything

**Comment by LinuxPhreak** [comment]
FYI: Because the server I installed it on doesn't have a DE I used another computer on the network to go to the location. The computer I used to get to the server was Fedora 28 with Firefox 61

**Comment by compewter** [comment]
Hey @LinuxPhreak thanks for trying out whoof! This will happen if the admin socket isn't able to connect to the server. I'll look into adding a notification for when this is happening. 

Are you able to see what whoof is logging on your server? This could be happening if the server is crashing or if the port is blocked by your firewall.

Also make sure you've pulled down the latest version and npm install (both client and server) if you haven't already. There were some big dependency updates done about a month ago. Might be easier to just nuke the folder and go through the setup instructions again.

Let me know if a fresh install/update doesn't fix it and if not what you're seeing in the logs.

**Comment by compewter** [comment]
Let me know if you're still playing around with this
